version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 10000
        USER_GID: 10000
    ports:
      - '7071:7071'
    init: true
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

  # run azurite and expose the relevant ports
  azurite:
    image: 'mcr.microsoft.com/azure-storage/azurite'
    ports:
      - '10100:10000'
      - '10101:10001'
      - '10102:10002'

  # azurite2:
  #   image: 'mcr.microsoft.com/azure-storage/azurite'
  #   ports:
  #     - '10200:10000'
  #     - '10201:10001'
  #     - '10202:10002'

  database:
    build:
      context: .
      dockerfile: DockerfileSqlServer
    ports:
      - '6000:1433'
    environment:
      - SA_PASSWORD=quoosugTh5
      - MSSQL_SA_PASSWORD=quoosugTh5
    # command: >
    #   /opt/mssql/bin/sqlservr & && 
    #   /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P "quoosugTh5" -i /var/opt/mssql/data/LoadAdventureworksDb.sql >> /startup.log &&
    #   echo "Startup done" >> /startup.log

    # volumes:
    #   - ./sql-scripts:/docker-entrypoint-initdb.d
    # command: ['/bin/bash', '-c', '/docker-entrypoint-initdb.d/your-script.sql']
