name: Build and Test with DevContainer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step to set up Docker, in case the container needs building
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step to build the DevContainer image
    - name: Build DevContainer
      run: |
        docker build -t devcontainer .devcontainer

    # Step to run .NET tests from the host using the built environment
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Adjust version according to your project

    - name: Restore dependencies
      run: dotnet restore src/Adapter.Sql.Tests/Adapter.Sql.Tests.csproj

    - name: Build the solution
      run: dotnet build src/Adapter.Sql.Tests/Adapter.Sql.Tests.csproj --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test src/Adapter.Sql.Tests/Adapter.Sql.Tests.csproj --no-restore --configuration Release
