name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install containerd.io
      run: |
        sudo apt-get update
        sudo apt-get install -y containerd.io

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Build devcontainer
      run: |
        docker-compose -f .devcontainer/docker-compose.yml build

    - name: Start services
      run: |
        docker-compose -f .devcontainer/docker-compose.yml up -d

    - name: Restore dependencies
      run: dotnet restore src/AllProjects.sln

    - name: Build all projects
      run: dotnet build --no-restore src/AllProjects.sln

    - name: Run tests
      run: dotnet test --no-build --verbosity normal src/AllProjects.sln
